### ISSUE TITLE
Adding multiple links requires changing link source to activate submit button

### ISSUE THREAD

**Issue by Omranic** [GoogleDeveloperExperts/experts-app-web#148] opened 2016-11-22 22:43 UTC
When adding multiple links to an activity, it appears we've to "Save" button is always disabled unless we change link source from current link source (recently selected link source) to something else, then choosing previous value again!

**Comment by cfjedimaster** [comment] 2016-12-05 15:13
I had the same thing today, except it was the 2nd link in my session. By that I mean I had added an activity with one link, and it worked. I then worked on my second activity, and had this bug. The same fix helped.

**Comment by justinribeiro** [comment] 2016-12-29 17:57
Duplicate of #130.

**Closed as completed by justinribeiro** 2016-12-29 17:57 UTC
Labels: duplicate
