### ISSUE TITLE
Activity Creation - Activity Metrics & URL does not save

### ISSUE THREAD

**Issue by mariepatriarche** [GoogleDeveloperExperts/experts-app-web#85] opened 2016-08-18 07:15 UTC
Steps:
Created Activity
Then pressed the + button added numbers and submit, it allowed me to submit but didnt save numbers
Re-pressed+ and now the Submit Button would not do any action/take me anywhere

![screenshot 2016-08-18 at 9 12 06 am](https://cloud.githubusercontent.com/assets/9035600/17765075/dd1b0d84-6523-11e6-907b-5d2f4aa1aef3.png)

Then I exit and also gets stuck on this screen
![screenshot 2016-08-18 at 9 14 21 am](https://cloud.githubusercontent.com/assets/9035600/17765134/339882a4-6524-11e6-9f7d-9837dba03098.png)

Most of the data i entered didnt save ( Metrics, Link to activity post etc.)

**Comment by mariepatriarche** [comment] 2016-08-18 07:18
Eventually when I exited and when on my activities, it seems everything saved, so the bug is more in the adding actoviy flow where you dont see anything being recorded and risk of adding activity again/duplicate
![screenshot 2016-08-18 at 9 17 25 am](https://cloud.githubusercontent.com/assets/9035600/17765200/a127717c-6524-11e6-91a9-f2e8285c65ac.png)

**Comment by LostInBrittany** [comment] 2016-08-18 12:50
Hmmm, I'll try to reproduce (and correct it) tonight, thanks!

**Comment by reicek** [comment] 2016-08-18 13:36
This screen shots doesn't reflect the current version of this app @mariepatriarche  . Please refresh your browser windows to get the most recent version of the app.

Several fixes are coming out for Activity Create this week =)

![image](https://cloud.githubusercontent.com/assets/3601209/17775627/1b891df6-6527-11e6-8d90-ea3ab57b968e.png)


Closing this issue.

**Comment by reicek** [comment] 2016-08-18 13:46
My bad, confused sections =/

**Comment by LostInBrittany** [comment] 2016-08-18 20:57
OK, I'm able to reproduce! It only happens when you try to add a new Activity Post on a newly create Activity Record without coming back to the main activity list, and the problem comes from a 503 error from the backend, I'm guessing that it's because I send it a bad info in that case.

Anyways, good catch, tricky bug, I'm going to try to solve it tonight...

**Comment by LostInBrittany** [comment] 2016-08-18 21:06
OK, I understand! The problem appears when you create an Activity Post and you set **no value** for one or more of the metrics, the backend tries to compute the total metrics and the no values confuses it:

```

Encountered unexpected error from ProtoRPC method implementation: TypeError (unsupported operand type(s) for +=: 'int' and 'NoneType') (/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/wsgi/service.py:191)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

I'm setting a by default 0 value

**Closed as completed** 2016-08-18 21:25 UTC
Labels: review needed
