### ISSUE TITLE
"Submit" button for activity entry is off-screen, unaccessible from tab-focus.

### ISSUE THREAD

**Issue by kanawish** [GoogleDeveloperExperts/experts-app-web#154] opened 2017-02-03 12:08 UTC
Had to resize browser to get access to submit button.

**Comment by justinribeiro** [comment] 2017-02-06 17:12
I believe this is a duplicate of #134 due to the lack of scrollable region. I'll check.

**Comment by justinribeiro** [comment] 2017-02-25 03:08
Resolved in https://github.com/GoogleDeveloperExperts/experts-app-web/releases/tag/2.0.7

**Closed as completed by justinribeiro** 2017-02-25 03:08 UTC
Labels: bug, hold
