### ISSUE TITLE
Edit Activity Links not scrollable

### ISSUE THREAD

**Issue by Omranic** [GoogleDeveloperExperts/experts-app-web#147] opened 2016-11-22 18:38 UTC
Edit Activity -> Links section is not scrollable even when contains many links, makes it impossible to know what links been added, or the ability to modify any

![screenshot 2016-11-22 20 36 08](https://cloud.githubusercontent.com/assets/406705/20536854/72f44fee-b0f3-11e6-9df1-ddcc495226d1.png)

**Comment by Scarygami** [comment] 2016-11-22 19:59
Probably related to #134

For this specific case I discovered that it helps to close the activity and open it again, since it then recenters properly giving a bit more space. The links are loaded dynamically after the activity is opened, so the size of the element for the first positioning is "wrong".

**Comment by Omranic** [comment] 2016-11-22 22:40
@Scarygami Well, even after closing and re-opening the activity it still not well positioned! The above screen actually for a re-opened activity which contains 10+ links (macOS, Chrome)

**Comment by justinribeiro** [comment] 2016-12-29 17:59
Duplicate of #134.

**Closed as completed by justinribeiro** 2016-12-29 17:59 UTC
Labels: duplicate
